/* 
    Bot generated by NOBOT v.0.0.1 platform 23.03.21 
    Author: Bohdan Sokolovskyi
    Version: 0.0.1
*/
'use strict'

const wisteria = require("../src/wisteria");

// vars
let startCommand = '/start';
let greetings = ['Hi', 'Hello', 'Hey you'];
let userName = null;

// state actions
function actA(input, send) {
    if (input == startCommand) {
        // send "Hello",
        actB(send);
    } else {
        actDefault(send);
    }
}

function actB(send) {
    // send "What is your name?"
    // hot go to in type state ?
}

function actC(input, send) {
    userName = input;
    // say "Hello" input;
    // go to actA
}

function actDefault(send) {
    // say "Sorry, i can't understand you"
    // go to actA;
}
