/* 
    Bot generated by NOBOT v.0.0.1 platform 23.03.21 
    Authror: Bohdan Sokolovskyi
    Version: 0.0.1
*/
'use strict'

const wisteria = require("../wisteria");

const botOptions = new wisteria.Options("TestBot", 8081);
const botInstance = new wisteria.Bot();


